### PR TITLE
Laravel 5.3 Shift

### PR DESCRIPTION
**Pull request by laravel-shift**
This pull request includes the changes for upgrading to Laravel 5.3. Feel free to commit any additional changes to the `laravel-5.3-shift` branch.

**Before merging**, you should:

- Checkout the `laravel-5.3-shift` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the pre-commands fail, add `--no-scripts`)
- Thoroughly test your application

If you would like more help with your upgrade, check out the new [human services from Laravel Shift](https://laravelshift.com/human-services).

### CODE REVIEW

**Comment by laravel-shift** [comment]
ℹ Laravel 5.3 no longer includes the `app/Events` folder by default. It is created for you when you make your first *Event* using `artisan`. I did not remove yours as it appears to differ from the default. However, if your app does not use *Events*, you can remove this folder manually to keep your app streamlined.

**Comment by laravel-shift** [comment]
❌ I was not able to update your `app/Providers/AuthServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/AuthServiceProvider.php) and merge the new changes.

**Comment by laravel-shift** [comment]
❌ I was not able to update your `app/Providers/EventServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/EventServiceProvider.php) and merge the new changes.

**Comment by laravel-shift** [comment]
❌ I was not able to update your `app/Providers/RouteServiceProvider.php`. You will need to compare yours against the [5.3 version](https://github.com/laravel-shift/laravel-5.3/blob/master/app/Providers/RouteServiceProvider.php) and merge the new changes.

**Comment by laravel-shift** [comment]
⚠ Laravel 5.3 now includes a top-level `routes` folder. In addition, it separates routes into *API*, *console*, and *web* files.I have included a default `routes/api.php` and `routes/console.php` as well as migrated your `app/Http/routes.php` to `routes/web.php`. You should review your routes to see if they should be separated into one of the new route files.

**Comment by laravel-shift** [comment]
❌ In Laravel 5.3, the `first`, `last`, and `contains` methods now pass the *value* as the first parameter to the given callback instead of the *key*. You should verify these callbacks are still working properly.

I found potential uses of these methods in:

- [ ] app/Console/Commands/ClassifyMLPMA.php

**Comment by laravel-shift** [comment]
❌ I could not upgrade the following configuration files since they differed from the 5.2 defaults. You need to compare these configuration files against the [Laravel 5.3 configuration files](https://github.com/laravel-shift/laravel-5.3/blob/master/config) and merge any changes:

- [ ] config/auth.php
- [ ] config/cache.php
- [ ] config/database.php
- [ ] config/services.php
- [ ] config/session.php

**Comment by laravel-shift** [comment]
❌ I could not upgrade the following project files since they differed from the 5.2 defaults. You need to compare these project files against the [default Laravel 5.3 versions](https://github.com/laravel-shift/laravel-5.3/) and merge any changes:

- [ ] gulpfile.js
- [ ] package.json

**Comment by laravel-shift** [comment]
⚠ The `lists()` method on Collection objects was [deprecated in Laravel 5.2](https://laravel.com/docs/5.3/upgrade#5.2-deprecations) and removed in Laravel 5.3. I replaced usages of `lists()` with `pluck()`, you can review the *Shift deprecations* commit to verify this change.

**Comment by laravel-shift** [comment]
❌ Laravel 5.3 requires PHP 5.6.4+. You have an existing dependency for PHP in your `composer.json`. Ensure it meets the new version requirement of `>=5.6.4`.

**Comment by laravel-shift** [comment]
❌ Laravel 5.3 has a development dependency for `phpunit/phpunit` of `~5.0`. You have a modified dependency for `phpunit/phpunit` in your `composer.json`. Ensure it meets the new version requirement of `~5.0`.

**Comment by laravel-shift** [comment]
❌ Laravel 5.3 has a development dependency for `symfony/css-selector` of `3.1.*`. You have a modified dependency for `symfony/css-selector` in your `composer.json`. Ensure it meets the new version requirement of `3.1.*`.

**Comment by laravel-shift** [comment]
❌ Laravel 5.3 has a development dependency for `symfony/dom-crawler` of `3.1.*`. You have a modified dependency for `symfony/dom-crawler` in your `composer.json`. Ensure it meets the new version requirement of `3.1.*`.

**Comment by laravel-shift** [comment]
❌ Laravel 5.3 `where` performs a "loose" comparison. In addition, the *strict* parameter was removed. If you need to perform a "strict" comparison, you can use `whereStrict` instead.

You should review the following usages of `where` to ensure you do not require "strict" compaison:

- [ ] app/Traits/TrackCollection.php
- [ ] app/Console/Commands/RebuildTrackCache.php
- [ ] app/Console/Commands/ClearTrackCache.php
- [ ] app/Console/Commands/MigrateOldData.php
- [ ] app/Console/Commands/FixMLPMAImages.php
- [ ] app/Commands/EditTrackCommand.php
- [ ] app/Commands/EditAlbumCommand.php
- [ ] app/Commands/UploadTrackCommand.php
- [ ] app/Commands/ParseTrackTagsCommand.php
- [ ] app/Commands/GenerateTrackFilesCommand.php
- [ ] app/Commands/ToggleFavouriteCommand.php
- [ ] app/Commands/AddTrackToPlaylistCommand.php
- [ ] app/Commands/CreateCommentCommand.php
- [ ] app/Commands/ToggleFollowingCommand.php
- [ ] app/Jobs/EncodeTrackFile.php
- [ ] app/Models/Notification.php
- [ ] app/Models/Track.php
- [ ] app/Models/User.php
- [ ] app/Models/ResourceUser.php
- [ ] app/Models/TrackFile.php
- [ ] app/Http/Controllers/AuthController.php
- [ ] app/Http/Controllers/Api/Web/StatsController.php
- [ ] app/Http/Controllers/Api/Web/AlbumsController.php
- [ ] app/Http/Controllers/Api/Web/AccountController.php
- [ ] app/Http/Controllers/Api/Web/ImagesController.php
- [ ] app/Http/Controllers/Api/Web/ArtistsController.php
- [ ] app/Http/Controllers/Api/Web/PlaylistsController.php
- [ ] app/Http/Controllers/Api/Web/NotificationsController.php
- [ ] app/Http/Controllers/Api/Web/CommentsController.php
- [ ] app/Http/Controllers/Api/Web/TracksController.php
- [ ] app/Http/Controllers/Api/Web/TaxonomiesController.php
- [ ] app/Providers/RouteServiceProvider.php
- [ ] app/Library/Notifications/Drivers/NativeDriver.php
- [ ] app/Library/Notifications/RecipientFinder.php
- [ ] database/legacy_migrations/2015_11_05_004145_AddUnclassifiedTrackType.php
- [ ] database/legacy_migrations/2015_10_26_231224_AddTrackSourceColumn.php
- [ ] database/legacy_migrations/2016_06_05_193032_enforce_unique_slugs.php
- [ ] database/migrations/2016_07_10_000354_add_deleted_at_column_to_activities.php
- [ ] routes/web.php

**Comment by laravel-shift** [comment]
❌ In Laravel 5.3, Eloquent scopes now respect the leading boolean of scope constraints. If you are starting your scope with an `orWhere` constraint it will no longer be converted to a normal `where`.

You should review the following usages of `orWhere` to ensure you're not starting your constraints with it:

- [ ] app/Http/Controllers/Api/Web/TracksController.php

**Comment by laravel-shift** [comment]
❌ In Laravel 5.3, the `JoinClause` class has been rewritten to unify its syntax with the query builder. The optional `$where` parameter of the `on` clause and the `bindings` property have been removed.

You should review the following usages of `join` to ensure you're not using these features:

- [ ] app/Console/Commands/FixMLPMAImages.php
- [ ] app/Models/Notification.php
- [ ] app/Models/Playlist.php
- [ ] app/Models/Track.php
- [ ] app/Models/Album.php
- [ ] app/Http/Controllers/Api/Web/PlaylistsController.php
- [ ] app/Http/Controllers/Api/Web/TracksController.php
- [ ] database/migrations/2016_07_10_000354_add_deleted_at_column_to_activities.php

**Comment by laravel-shift** [comment]
❌ The Query Builder returns collections, instead of plain arrays, in Laravel 5.3. You will need to upgrade your code to use collections or chain the `all()` method onto your query to return a plain array.

You should review the following usages of Query Builder:

- [ ] app/Console/Commands/MigrateOldData.php
- [ ] app/Console/Commands/RefreshCache.php
- [ ] app/Console/Commands/ClassifyMLPMA.php
- [ ] app/Console/Commands/FixMLPMAImages.php
- [ ] app/Commands/EditTrackCommand.php
- [ ] app/Commands/RemoveTrackFromPlaylistCommand.php
- [ ] app/Commands/EditAlbumCommand.php
- [ ] app/Commands/MergeAccountsCommand.php
- [ ] app/Commands/ToggleFavouriteCommand.php
- [ ] app/Commands/AddTrackToPlaylistCommand.php
- [ ] app/Jobs/Job.php
- [ ] app/Jobs/EncodeTrackFile.php
- [ ] app/Models/Playlist.php
- [ ] app/Models/ResourceLogItem.php
- [ ] app/Models/Track.php
- [ ] app/Models/Genre.php
- [ ] app/Models/ShowSong.php
- [ ] app/Models/User.php
- [ ] app/Models/Comment.php
- [ ] app/Models/Album.php
- [ ] app/Http/Controllers/AuthController.php
- [ ] app/Http/Controllers/Api/Web/StatsController.php
- [ ] app/Http/Controllers/Api/Web/TaxonomiesController.php
- [ ] app/Library/Search.php
- [ ] database/seeds/GenreTableSeeder.php
- [ ] database/seeds/ShowSongTableSeeder.php
- [ ] database/legacy_migrations/2015_11_05_004145_AddUnclassifiedTrackType.php
- [ ] database/legacy_migrations/2015_05_25_011121_create_track_files_table.php
- [ ] database/legacy_migrations/2013_09_10_014644_create_latest_column.php
- [ ] database/legacy_migrations/2013_07_28_034328_create_songs_table.php
- [ ] database/legacy_migrations/2015_10_26_231224_AddTrackSourceColumn.php
- [ ] database/legacy_migrations/2016_06_05_221208_add_timestamps_to_show_songs.php
- [ ] database/legacy_migrations/2013_06_07_003952_create_users_table.php
- [ ] database/legacy_migrations/2015_09_05_113647_add_new_indices.php
- [ ] database/legacy_migrations/2013_07_26_230827_create_images_table.php
- [ ] database/legacy_migrations/2016_06_05_193032_enforce_unique_slugs.php
- [ ] database/legacy_migrations/2016_06_15_075023_fix_cache_table.php
- [ ] database/legacy_migrations/2013_06_27_015259_create_tracks_table.php
- [ ] database/legacy_migrations/2016_01_01_001340_update_model_namespaces_in_revisions.php
- [ ] database/legacy_migrations/2015_10_28_162655_AddTrackFilesForDeletedTracks.php
- [ ] database/legacy_migrations/2016_01_23_062640_EnforceUniqueTracksInPlaylists.php
- [ ] database/migrations/2016_06_26_225535_create_licenses_table.php
- [ ] database/migrations/2016_06_26_225535_create_roles_table.php
- [ ] database/migrations/2016_06_26_225535_create_show_songs_table.php
- [ ] database/migrations/2016_07_14_154357_MysqlToPostgres.php
- [ ] database/migrations/2016_07_10_000354_add_deleted_at_column_to_activities.php
- [ ] database/migrations/2016_06_26_225535_create_track_types_table.php

**Comment by laravel-shift** [comment]
ℹ If you are using *Queues*, you no longer need to specify the `--daemon` option when calling the `queue:work`. This is assumed in Laravel 5.3. Use the `--once` option to process a single job.

If you are using the `database` driver, you will need to update your `jobs` and `failed_jobs` table. Review the *Queue* section of the [Laravel 5.3 Upgrade Guide](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0) for more details and feel free to use the [migrations from Laravel Shift](https://github.com/laravel-shift/laravel-5.3/tree/master/database/migrations).

**Comment by laravel-shift** [comment]
ℹ Laravel 5.3 updated several of the default assets as well as adding support for [Vue.js](https://vuejs.org). If you are using Laravel to [compile assets](https://laravel.com/docs/5.3/elixir) you may want to review the latest versions of [`resources/assets/js/app.js`](https://github.com/laravel-shift/laravel-5.3/blob/master/resources/assets/js/app.js) and [`resources/assets/sass/app.scss`](https://github.com/laravel-shift/laravel-5.3/blob/master/resources/assets/sass/app.scss) and update your project accordingly.

**Comment by laravel-shift** [comment]
⚠ Laravel 5.3 added configuration for your application name in `config/app.php`. Be sure to set this value as it is used in notifications, like the password reset email.

**Comment by Lavoaster** [comment]
Going to push this up to staging for testing!

**Pull request merged**
