### PR TITLE
Resolves #45: start nginx on every VM boot

### LINKED ISSUE #45: Get NGINX to start on VM boot
Currently, NGINX does not start when the Vagrant VM boots up. This should not be the case.

### PR DESCRIPTION
**Pull request by kz**
Fixes issue #45.

### CODE REVIEW

**Comment by kz** [comment]
@Zeusking19 I don't have a test environment set up right now. Can you test this on your end and comment on the results?

**Comment by Zeusking19** [comment]
@kz This doesn't appear to be working.

**Comment by Zeusking19** [comment]
Vagrantfile:29: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '(' 
...o service nginx restart", run "always"
                                                 ^

**Comment by kz** [comment]
@Zeusking19  Added a colon. Try now!

**Comment by Feld0** [comment]
@kz squash the commits for this one. A trivial fix like that doesn't warrant its own commit if it's not on master.

It would also be better to refer to the `/vagrant/vagrant/copy-and-restart-configs.sh` script instead of restarting nginx directly - that script updates config files and restarts PHP as well.

**Comment by kz** [comment]
@Feld0 `copy-and-restart-configs.sh` is only run during full (re)provisions. This commit was adapted from [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile) where they placed the line in the Vagrantfile itself.

**Comment by Feld0** [comment]
But it's a tiny part of the provisioning process - it'll make sure that nginx and php-fpm are both running (and potentially other services, too).

**Comment by kz** [comment]
@Feld0 Would this be fine?
@Zeusking19 Mind testing?

**Comment by Feld0** [comment]
@kz Use the absolute path to the script.

**Comment by Feld0** [comment]
@kz: Looks good to me! :+1: 
@Zeusking19, test this out and merge it if it works.

**Comment by Zeusking19** [comment]
Works great. :+1:

**Pull request merged**
