### PR TITLE
Laravel 5.2 Shift

### PR DESCRIPTION
**Pull request by laravel-shift**
This pull request includes the changes for upgrading to Laravel 5.2. Feel free to commit any additional changes to the `laravel-5.2-shift` branch.

**Before merging**, you should:

- Checkout the `laravel-5.2-shift` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the pre-commands fail, add `--no-scripts`)
- Thoroughly test your application

If you would like more help with your upgrade, check out the new [human services from Laravel Shift](https://laravelshift.com/human-services).

### CODE REVIEW

**Comment by laravel-shift** [comment]
❌ Laravel 5.2 modified the default Middleware. Since your middleware differs from the Laravel 5.1 default, you will need to compare the following middleware against the [5.2 versions](https://github.com/laravel-shift/laravel-5.2/tree/master/app/Http/Middleware) and merge any changes.

- [ ] app/Http/Middleware/Authenticate.php
- [ ] app/Http/Middleware/EncryptCookies.php
- [ ] app/Http/Middleware/RedirectIfAuthenticated.php

**Comment by laravel-shift** [comment]
⚠ Laravel 5.2 adds *Middleware Groups* for convenience. Since this may require changes to your routes and controllers, I did not upgrade `app/Http/Kernel.php`. You should review [Middleware Groups](http://laravel.com/docs/5.2/middleware#middleware-groups) in more detail. When ready, merge your `app/Http/Kernel.php` with the [5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/app/Http/Kernel.php) and update your routes/controllers manually.

**Comment by laravel-shift** [comment]
❌ The Authentication configuration changed significantly in Laravel 5.2. Since your `config/auth.php` differs from the Laravel 5.1 default, you will need to compare yours against the [5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/config/auth.php) and merge any changes.

**Comment by laravel-shift** [comment]
ℹ Laravel 5.2 changed the value of `$redirectTo` from `/home` to `/` in `app/Http/Controllers/Auth/AuthController.php`. I did not make this change since you may have customized it for your app. However, you may wish to change this if you are not using *Auth* or if you want to follow the latest Laravel conventions.

**Comment by laravel-shift** [comment]
❌ Laravel 5.2 condenses the default User model dramatically. Since your `app/Models/User.php` differs from the Laravel 5.1 default, you will need to compare yours against the [5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/app/User.php) and merge any changes.

**Comment by laravel-shift** [comment]
❌ `pluck`, `keys`, `zip`, `collapse`, `flatten`, `flip` now return a collection in Laravel 5.2. You should review your usage of these methods.

I found potential uses of these methods in:

- [ ] app/Models/Playlist.php
- [ ] app/Models/Track.php
- [ ] app/Models/User.php
- [ ] app/Models/Album.php
- [ ] app/Http/Controllers/Api/Web/PlaylistsController.php

**Comment by laravel-shift** [comment]
❌ `slice`, `chunk`, and `reverse` methods now preserve keys on the collection in Laravel 5.2. You should review your usage of these methods.

I found potential uses of these methods in:

- [ ] app/Console/Commands/RebuildTrackCache.php
- [ ] app/Console/Commands/VersionFiles.php
- [ ] app/Console/Commands/RebuildFilesizes.php
- [ ] app/Console/Commands/RebuildSearchIndex.php
- [ ] app/Jobs/UpdateTagsForRenamedGenre.php
- [ ] app/Jobs/DeleteShowSong.php
- [ ] app/Jobs/UpdateTagsForRenamedShowSong.php
- [ ] app/Jobs/DeleteGenre.php

**Comment by laravel-shift** [comment]
ℹ Laravel 5.2 updated the `database` session driver. If you are using the `database` driver, you need to add the `user_id` (nullable integer), `ip_address` (nullable string), and `user_agent` (text) columns to your session database table.

**Comment by laravel-shift** [comment]
⚠ I was unable to update `phpunit.xml` since yours differed from the Laravel default. You need to compare your `phpunit.xml` with the [Laravel 5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/phpunit.xml) and merge any changes.

**Comment by laravel-shift** [comment]
❌ Laravel 5.2 updated the `public/.htaccess` to handle the *Authorization* header. Since your `public/.htaccess` file differed from the Laravel default, you need to review the [Laravel 5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/public/.htaccess) and merge any changes.

**Comment by laravel-shift** [comment]
❌ Laravel 5.2 updated some of the default validation messages. Since your `resources/lang/en/validation.php` differed from the Laravel default, you need to review the [Laravel 5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/resources/lang/en/validation.php) and merge any changes.

**Comment by laravel-shift** [comment]
⚠ Laravel 5.2 no longer registers the `Input` facade by default. While the `Input` facade is still available, Laravel 5 prefers using the `Request` facade or the `$request` object within *Controllers*. Review the [HTTP Requests](https://laravel.com/docs/5.2/requests) documentation for more details.

I changed the following files to use the `Request` facade. However, you should review them to see if you can use the `$request` object directly.

- [ ] app/Commands/UploadTrackCommand.php
- [ ] app/Http/Controllers/AuthController.php
- [ ] app/Http/Controllers/Api/Web/GenresController.php
- [ ] app/Http/Controllers/Api/Web/FollowController.php
- [ ] app/Http/Controllers/Api/Web/AlbumsController.php
- [ ] app/Http/Controllers/Api/Web/AccountController.php
- [ ] app/Http/Controllers/Api/Web/ArtistsController.php
- [ ] app/Http/Controllers/Api/Web/PlaylistsController.php
- [ ] app/Http/Controllers/Api/Web/NotificationsController.php
- [ ] app/Http/Controllers/Api/Web/CommentsController.php
- [ ] app/Http/Controllers/Api/Web/ShowSongsController.php
- [ ] app/Http/Controllers/Api/Web/SearchController.php
- [ ] app/Http/Controllers/Api/Web/TracksController.php
- [ ] app/Http/Controllers/Api/Web/FavouritesController.php
- [ ] app/Library/PfmValidator.php

**Comment by laravel-shift** [comment]
❌ I could not upgrade the following configuration files since they differed from the 5.1 defaults. You need to compare these configuration files against the [default Laravel 5.2 configuration files](https://github.com/laravel-shift/laravel-5.2/tree/master/config) and merge any changes:

- [ ] config/broadcasting.php
- [ ] config/cache.php
- [ ] config/database.php
- [ ] config/filesystems.php
- [ ] config/mail.php
- [ ] config/services.php
- [ ] config/session.php
- [ ] config/queue.php

**Comment by laravel-shift** [comment]
ℹ Laravel 5.2 removed the `pretend` mail configuration option. If you were using `pretend`, use the `log` driver instead.

**Comment by laravel-shift** [comment]
⚠ Laravel 5.2 upgraded some of the Node package dependencies. You should to compare your `package.json` with the [Laravel 5.2 version](https://github.com/laravel-shift/laravel-5.2/blob/master/package.json) to update your dependencies.

**Comment by Lavoaster** [comment]
Wait, is this actually done?

**Comment by logic-dev** [comment]
Yarrrrrrr

**Comment by Lavoaster** [comment]
It's going to production!

**Pull request merged**
